# PYTHON

FROM python:2.7-slim-stretch

ENV APPDIR=/usr/src/app

RUN mkdir -p $APPDIR
WORKDIR $APPDIR

COPY app/requirements.txt $APPDIR/

RUN apt update
RUN apt install --no-install-recommends -y gcc  g++

RUN pip install -r requirements.txt

COPY app/ $APPDIR

RUN chmod -R +x $APPDIR/

COPY run.sh /
RUN chmod +x /run.sh
CMD ["/run.sh"]
