# PYTHON

#FROM python:2.7-slim-stretch
FROM python:2.7-alpine

ENV APPDIR=/usr/src/app

RUN mkdir -p $APPDIR
WORKDIR $APPDIR

COPY app/requirements.txt $APPDIR/

#RUN apt update 


RUN apk update && \
    apk add --virtual build-deps gcc python-dev musl-dev && \
    apk add postgresql-dev
    
#RUN apt install --no-install-recommends -y gcc make
RUN pip install -r requirements.txt

COPY app/ $APPDIR

