version : '2'

services:
    nginx:
        build: ../nginx/
        ports:
            - "$NGINX_PORT:80"
        volumes:
            - /www/static
        volumes_from:
            - django
        links:
            - django:django
        depends_on:
            - django         
    django:
        build: 
            context: ../
            dockerfile: Dockerfile.django
        expose:
            - "8000"
        volumes:
            - djangostatic:/usr/src/app/static
            - djangologs:/var/log/django
            - djangomigrations:/djangomigrations
        links:
            - postgres:postgres
        env_file: 
            - .env
        depends_on:
            - postgres

    postgres:
        image: postgres:9.6-alpine
        expose:
            - "5432"
        volumes:
            - pgdata:/var/lib/postgresql/data/
    
volumes:
    pgdata:
    djangologs:
    djangostatic:
    djangomigrations:
